### ISSUE TITLE
Incorrect Slope Formula

### ISSUE THREAD

**Issue by CBdocs82** [learn-co-curriculum/dsc-0-10-06-simple-linear-regression#3]
Hello,

I noticed an incorrect slope formula in the Simple Linear Regression Lab.

_The slope (m) of a line is the change in Y over the change in X (Δy/Δx shown above). For example, a slope of 4/3 means as the x-value increases by 4 units, the y-value moves up by 3 units on average._

I verified with the teacher aid Forest Polchow, who verified that it is y/x, not x/y. For example, in elementary schools they call this "rise over run."

Thanks,
Charles J. Barrios

**Comment by fpolchow** [comment]
typo corrected
